# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ci-vi-axe

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ci-vi-axe:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20, 22, 24]

    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v6
        with:
          run_install: false
      - run: pnpm install --frozen-lockfile --filter vi-axe... --filter vi-axe-test...
      - run: pnpm run --filter vi-axe build
      - run: pnpm run --filter vi-axe test
      - run: pnpm run --filter vi-axe-test check-types
      - run: pnpm run --filter vi-axe-test test
